export type FaseNumero = 'fase_1' | 'fase_2' | 'fase_3' | 'fase_4' | 'fase_5';
export type WorkflowStatus = 'fase_1' | 'fase_2' | 'fase_3' | 'fase_4' | 'fase_5' | 'concluido' | 'cancelado';
export type FaseStatus = 'pendente' | 'em_progresso' | 'concluido' | 'incompleto';
export type ItemStatus = 'pendente' | 'concluido' | 'pulado' | 'na';

export interface ChecklistItemData { id: string; status: ItemStatus; timestamp?: string; observacao?: string; valor?: string | number; }
export interface ChecklistItemConfig { id: string; label: string; descricao: string; obrigatorio: boolean; automatico: boolean; grupo?: string; permiteNA?: boolean; mostrarConteudo?: boolean; botaoCopiar?: boolean; campoURL?: boolean; campoQuantidade?: boolean; permiteReprovar?: boolean; campoFeedback?: boolean; }
export interface FaseConfig { numero: FaseNumero; nome: string; descricao: string; icone: string; items: ChecklistItemConfig[]; }
export interface FaseData { status: FaseStatus; completed_at?: string; checklist: Record<string, ChecklistItemData>; feedback?: string; }
export interface MetricasPost { views?: number; likes?: number; comments?: number; saves?: number; shares?: number; reach?: number; follows?: number; }
export interface PostpackWorkflow { id: string; postpack_id: string; status: WorkflowStatus; created_at: string; updated_at: string; completed_at?: string; created_by?: string; approved_by?: string; fase_1: FaseData; fase_2: FaseData; fase_3: FaseData; fase_4: FaseData; fase_5: FaseData; published_url?: string; published_at?: string; metricas_24h?: MetricasPost; metricas_7d?: MetricasPost; notas?: string; }
export interface PostpackResumo { id: string; title: string; objective: string; format: string; pillar?: string; hook_text?: string; script?: string; caption?: string; scheduled_for?: string; status: string; }
export interface WorkflowStepperProps { currentFase: FaseNumero; workflow: PostpackWorkflow; onFaseClick?: (fase: FaseNumero) => void; }
export interface FaseChecklistProps { fase: FaseNumero; config: FaseConfig; data: FaseData; postpack: PostpackResumo; onItemChange: (itemId: string, data: Partial<ChecklistItemData>) => void; onAvancar: () => void; onVoltar: () => void; podeAvancar: boolean; }
export interface ChecklistItemProps { config: ChecklistItemConfig; data: ChecklistItemData; postpack: PostpackResumo; onChange: (data: Partial<ChecklistItemData>) => void; disabled?: boolean; }
export interface ConfirmacaoModalProps { isOpen: boolean; onClose: () => void; onConfirm: (observacao?: string) => void; item: ChecklistItemConfig; conteudo?: string; }
export interface AlertaContinuarModalProps { isOpen: boolean; onClose: () => void; onVoltar: () => void; onContinuar: () => void; itensPendentes: ChecklistItemConfig[]; fase: FaseNumero; }
export interface RelatorioFinalProps { workflow: PostpackWorkflow; postpack: PostpackResumo; }
export interface UseWorkflowReturn { workflow: PostpackWorkflow | null; postpack: PostpackResumo | null; loading: boolean; error: string | null; updateChecklist: (fase: FaseNumero, itemId: string, data: Partial<ChecklistItemData>) => Promise<void>; avancarFase: (force?: boolean) => Promise<boolean>; voltarFase: () => Promise<void>; finalizarWorkflow: () => Promise<void>; getCurrentFase: () => FaseNumero; getFaseProgress: (fase: FaseNumero) => number; canAdvance: (fase: FaseNumero) => boolean; getItensPendentes: (fase: FaseNumero) => ChecklistItemConfig[]; }
export interface UseChecklistReturn { items: Record<string, ChecklistItemData>; updateItem: (itemId: string, data: Partial<ChecklistItemData>) => void; getProgress: () => number; isComplete: () => boolean; getPendingItems: () => string[]; getSkippedItems: () => string[]; }
export interface CreateWorkflowInput { postpack_id: string; created_by?: string; }
export interface WorkflowFilters { status?: WorkflowStatus[]; created_after?: string; created_before?: string; limit?: number; offset?: number; }
export interface PostpackWorkflowRow { id: string; postpack_id: string; status: WorkflowStatus; created_at: string; updated_at: string; completed_at: string | null; created_by: string | null; approved_by: string | null; fase_1_status: FaseStatus; fase_1_completed_at: string | null; fase_1_checklist: Record<string, ChecklistItemData>; fase_2_status: FaseStatus; fase_2_completed_at: string | null; fase_2_checklist: Record<string, ChecklistItemData>; fase_2_feedback: string | null; fase_3_status: FaseStatus; fase_3_completed_at: string | null; fase_3_checklist: Record<string, ChecklistItemData>; fase_4_status: FaseStatus; fase_4_completed_at: string | null; fase_4_checklist: Record<string, ChecklistItemData>; fase_4_published_url: string | null; fase_4_published_at: string | null; fase_5_status: FaseStatus; fase_5_completed_at: string | null; fase_5_checklist: Record<string, ChecklistItemData>; metricas_24h: MetricasPost | null; metricas_7d: MetricasPost | null; notas: string | null; }
